#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
picom &
setxkbmap -option grp:alt_shift_toggle us,ru &
lxappearance &
nm-applet --indicator &
betterlockscreen -u ~/Pictures/fafa77aa3885c4d9689297d4cd8997b0.jpg &
~/.config/eww/bin/eww daemon
~/.config/eww/bin/eww open bar

bspc monitor -d 1 2 3 4 5 6

bspc config border_width          2
bspc config window_gap            10
bspc config focus_follows_pointer true

bspc config focused_border_color \#7aa2f7
bspc config normal_border_color \#787c99